### ISSUE TITLE
Check Foreman task for successful installation of errata

### ISSUE THREAD

**Issue by AnonJo** [stdevel/katprep#40] opened 2017-09-29 14:37 UTC
After sending the API call to Foreman to install errata for a host, the host, if it's a VM, gets directly rebooted if the needs-reboot flag or the reboot option is set and than the installation fails.

It should be checked if the installation task was successful prior to rebooting the host.

**Comment by stdevel** [comment] 2018-06-12 11:56
The problem is that rebooting VMs was not possible, back when I was developing this utility (*see also issue #4*); so I was implementing an workaround that triggers a reboot.

In the meantime, things have changed and Foreman offers this ability when adding the appropriate hypervisor as compute resource. The only requirement is that VM objects have been linked to hosts (*Infrastructure > Compute Resources > Select resource > Associate VMs*).

The current implementation simply fires a reboot after triggering the API call for installing errata. To fix this, it would be necessary to get the errata update task ID and wait for completion before triggering the reboot. On the other hand, this will prohibit parallel execution. My assumption is that triggering the reboot via the Foreman API would result in waiting until errata are installed. I'm going to test this.

The appropriate API call (`PUT /hosts/ID/power`) was introduced in Red Hat Satellite 6.3.

**Comment by stdevel** [comment] 2018-06-12 12:15
Verified assumption on Foreman 1.17.1 and Katello 3.6. Will revert workaround #4 as default behavior and implement an additional parameter for forcing the workaround.

Started work in branch `bug-errata_reboot-issue40`.

**Comment by stdevel** [comment] 2018-06-12 13:07
Reverted workaround from #4 in commit a1d9c85d49defa2c26e409f710f5451050fec334. Successfully tested with Foreman 1.17.1 and Katello 3.6.

**Comment by stdevel** [comment] 2018-06-12 13:13
Fixed in commit 7ab3fd04c89d74f23008516e344c933b22b77625.

**Closed by stdevel** 2018-06-12 13:13 UTC
Labels: bug, enhancement
